In [2]:
import pandas as pd
df = pd.read_csv("Dataset.csv")

In [3]:
df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
6460,18219522,Locale,1,New Delhi,"17, Community Centre, Next to PVR Anupam, Sake...",PVR Anupam Complex,"PVR Anupam Complex, New Delhi",77.207183,28.523323,"North Indian, Chinese, Mexican, Italian, Thai,...",...,Indian Rupees(Rs.),Yes,Yes,No,No,3,4.4,Green,Very Good,317

In [4]:
df["name length"] = df["Restaurant Name"].apply(len)

df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,name length
278,17342556,Houlihan's,216,Dubuque,"1795 Greyhound Park Rd, Dubuque, IA 52001",Dubuque,"Dubuque, Dubuque",-90.645294,42.516621,"American, Burger",...,No,No,No,No,2,3.6,Yellow,Good,117,10

In [5]:
df["address length"] = df["Address"].apply(len)

df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,name length,address length
5574,18424171,Brijwasi,1,New Delhi,"Building 1A, Shop 2, Batra Cinema Complex, Muk...",Mukherjee Nagar,"Mukherjee Nagar, New Delhi",77.215591,28.712279,"North Indian, Chinese, South Indian",...,No,No,No,1,0.0,White,Not rated,0,8,69

In [6]:
def encoder(x):
    if x=="No":
        return 0
    else:
        return 1

In [7]:
df["Has Table booking"] = df["Has Table booking"].apply(encoder)
df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,name length,address length
5533,304573,Chinese Corner,1,New Delhi,"19, Main Market, Moti Nagar, New Delhi",Moti Nagar,"Moti Nagar, New Delhi",77.142823,28.658819,"Fast Food, Chinese",...,No,No,No,1,0.0,White,Not rated,0,14,38

In [8]:

df["Has Online delivery"] = df["Has Online delivery"].apply(encoder)
df.sample()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,name length,address length
2179,310699,The Living Room - The Westin Sohna Resort & Spa,1,Gurgaon,"The Westin Sohna Resort & Spa, Vatika Complex,...","The Westin Sohna Resort & Spa, Sohna Road","The Westin Sohna Resort & Spa, Sohna Road, Gur...",77.142751,28.239367,Continental,...,0,No,No,4,3.7,Yellow,Good,45,47,91

In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("dataset.csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [13]:
df_model = df[[
    'Aggregate rating',
    'Votes',
    'Price range',
    'Has Table booking',
    'Has Online delivery'
]]

In [14]:
df_model['Has Table booking'] = df_model['Has Table booking'].map({'Yes': 1, 'No': 0})
df_model['Has Online delivery'] = df_model['Has Online delivery'].map({'Yes': 1, 'No': 0})

C:\Users\LIKITH V\AppData\Local\Temp\ipykernel_1356\431877988.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model['Has Table booking'] = df_model['Has Table booking'].map({'Yes': 1, 'No': 0})
C:\Users\LIKITH V\AppData\Local\Temp\ipykernel_1356\431877988.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model['Has Online delivery'] = df_model['Has Online delivery'].map({'Yes': 1, 'No': 0})

In [15]:
df_model.fillna(0, inplace=True)

C:\Users\LIKITH V\AppData\Local\Temp\ipykernel_1356\3445439971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model.fillna(0, inplace=True)

In [16]:
X = df_model.drop('Aggregate rating', axis=1)
y = df_model['Aggregate rating']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [19]:
y_pred = model.predict(X_test)

In [20]:
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

Mean Squared Error: 1.6768067245748604
R2 Score: 0.2633012163679982